import {chromium} from "playwright";
const browser=await chromium.launch({headless:true,args:["--no-sandbox"]});
try{
const page=await browser.newPage({viewport:{width:1360,height:920}});
const errors=[];
page.on("pageerror",e=>errors.push(e.message));
await page.goto("http://127.0.0.1:8765/resource-time-machine/",{waitUntil:"domcontentloaded"});
await page.waitForFunction(()=>document.getElementById("counts").textContent.includes("files"),{timeout:180000});
const fileCount=await page.locator("#counts").innerText();
if(!/2\d,\d{3}/.test(fileCount))throw Error("Resource catalog incomplete: "+fileCount);
await page.locator("#search").fill("title/fix_blk_logo.bmp");
await page.locator(".result").first().click();
await page.waitForFunction(()=>document.getElementById("load-status").textContent.includes("Showing original"),{timeout:90000});
const bmp=await page.locator("#new-preview img").count();
if(bmp!==1)throw Error("BMP image didn't render");
await page.locator("#search").fill("op_demo/op000.tga");
await page.locator(".result").first().click();
await page.waitForFunction(()=>document.getElementById("load-status").textContent.includes("Showing original"),{timeout:90000});
const pixels=await page.locator("#new-preview canvas").evaluate(c=>{
 const a=c.getContext("2d").getImageData(0,0,c.width,c.height).data;
 let pixels=0;for(let i=3;i<a.length;i+=4)if(a[i]>0)pixels++;
 return {w:c.width,h:c.height,pixels};
});
if(pixels.w!==256||pixels.h!==170||pixels.pixels<1000)throw Error("TGA preview was blank: "+JSON.stringify(pixels));
await page.locator("#search").fill("eventdata/data/c01.mev");
await page.locator(".result").first().click();
await page.waitForFunction(()=>document.getElementById("load-status").textContent.includes("Showing original"),{timeout:90000});
const mappedEvents=await page.locator("#new-preview .data-table tbody tr").count();
const mapCanvas=await page.locator("#new-preview .event-canvas").count();
if(mappedEvents<2||mapCanvas!==1)throw Error("Structured map event preview failed: "+mappedEvents+" entries");
await page.locator("#search").fill("message/src/b_bag.gmm");
await page.locator(".result").first().click();
await page.waitForFunction(()=>document.getElementById("load-status").textContent.includes("Showing original"),{timeout:90000});
const rows=await page.locator("#new-preview .data-table tbody tr").count();
if(rows<30)throw Error("GMM source dialogue rows missing: "+rows);
await page.locator("#search").fill("musical/dressup/anime_ue.ncg");
await page.locator(".result").first().click();
await page.waitForFunction(()=>document.getElementById("load-status").textContent.includes("Showing original")||document.getElementById("load-status").classList.contains("error"),{timeout:90000});
const ncgr=await page.locator("#load-status").innerText();
if(!ncgr.startsWith("Showing original"))throw Error("Raw source NCGR not rendered: "+ncgr);
const ncgPixels=await page.locator("#new-preview canvas").evaluate(c=>{
 const data=c.getContext("2d").getImageData(0,0,c.width,c.height).data;
 let visible=0;for(let i=3;i<data.length;i+=4)if(data[i]>0)visible++;
 return {width:c.width,height:c.height,visible};
});
if(ncgPixels.visible<20)throw Error("Raw source NCGR image is blank: "+JSON.stringify(ncgPixels));
console.log(JSON.stringify({files:fileCount,bmp,basicTga:pixels,mappedEvents,mapCanvas,gmmRows:rows,ncgrStatus:ncgr,ncgPixels,errors},null,2));
await page.screenshot({path:"/tmp/resource-time-machine.png"});
if(errors.length)throw Error("JS errors: "+errors.join("; "));
}finally{await browser.close();}
