import {u16,s16,u32,s32,w16,w32,magic} from './binary.js';

export function bgr555ToCss(v,a=255){ const r=v&31,g=(v>>>5)&31,b=(v>>>10)&31; const rr=(r<<3)|(r>>>2),gg=(g<<3)|(g>>>2),bb=(b<<3)|(b>>>2); return `rgba(${rr},${gg},${bb},${a/255})`; }
export function rgbToBgr555(hex){ const n=parseInt(hex.replace('#',''),16),r=(n>>>16)&255,g=(n>>>8)&255,b=n&255; return ((Math.round(r*31/255)&31)|((Math.round(g*31/255)&31)<<5)|((Math.round(b*31/255)&31)<<10))&0x7fff; }
export function bgr555ToHex(v){ const r=v&31,g=(v>>>5)&31,b=(v>>>10)&31; const f=x=>((x<<3)|(x>>>2)).toString(16).padStart(2,'0'); return `#${f(r)}${f(g)}${f(b)}`; }

export function findSection(data,name){ for(let pos=0x10;pos+8<=data.length;){ const size=u32(data,pos+4); if(size<8||pos+size>data.length) break; if(magic(data,pos,name)) return {offset:pos,size}; pos+=size;} return null; }

export class Nclr{
  constructor(data){ this.data=data; if(!magic(data,0,'RLCN')) throw new Error('Not NCLR'); const pos=0x10; if(!magic(data,pos,'TTLP')) throw new Error('NCLR missing TTLP'); let size=u32(data,pos+0x10),off=pos+0x18; if(!size||off+size>data.length){off=0x28;size=data.length-off;} this.offset=off; this.count=Math.min(256,Math.floor(size/2)); }
  raw(i){ return u16(this.data,this.offset+i*2); } hex(i){ return bgr555ToHex(this.raw(i)); } css(i){ return i===0?'rgba(0,0,0,0)':bgr555ToCss(this.raw(i)); }
  setHex(i,hex){ if(i<0||i>=this.count)return; w16(this.data,this.offset+i*2,rgbToBgr555(hex)); }
}

export class Ncgr{
  constructor(data){ this.data=data; if(!magic(data,0,'RGCN')) throw new Error('Not NCGR'); const p=0x10;if(!magic(data,p,'RAHC')) throw new Error('NCGR missing RAHC'); this.widthTiles=u16(data,p+8);this.heightTiles=u16(data,p+10);const depth=u32(data,p+12);this.bpp=depth===3?4:depth===4?8:0;if(!this.bpp)throw new Error(`Unsupported NCGR bit depth ${depth}`);this.characterType=u32(data,p+0x14);let size=u32(data,p+0x18);this.offset=p+0x20;if(!size||this.offset+size>data.length)size=data.length-this.offset;this.dataSize=size;this.tileCount=Math.floor(size/(this.bpp===4?32:64)); this.linear4=this.characterType===1&&this.bpp===4; this.renderStride=this.linear4?32:(this.widthTiles||16); }
  pixel(tile,x,y){ if(tile<0||tile>=this.tileCount||x<0||x>7||y<0||y>7)return 0; if(this.linear4){ const tx=tile%32,ty=Math.floor(tile/32),px=tx*8+x,py=ty*8+y,flat=py*256+px,byte=this.data[this.offset+(flat>>1)];return flat&1?byte>>>4:byte&15; } const pp=this.bpp===4?32:64,base=this.offset+tile*pp,idx=y*8+x;if(this.bpp===8)return this.data[base+idx];const v=this.data[base+(idx>>1)];return idx&1?v>>>4:v&15; }
  setPixel(tile,x,y,val){ val&=this.bpp===4?15:255; if(tile<0||tile>=this.tileCount)return; if(this.linear4){const tx=tile%32,ty=Math.floor(tile/32),flat=(ty*8+y)*256+(tx*8+x),o=this.offset+(flat>>1),v=this.data[o];this.data[o]=flat&1?((v&15)|(val<<4)):((v&240)|val);return;}const pp=this.bpp===4?32:64,idx=y*8+x,o=this.offset+tile*pp+(this.bpp===4?(idx>>1):idx);if(this.bpp===8)this.data[o]=val;else{const v=this.data[o];this.data[o]=idx&1?((v&15)|(val<<4)):((v&240)|val);} }
  dimensions(stride=this.renderStride){ return {w:stride*8,h:Math.ceil(this.tileCount/stride)*8}; }
  pixelAt(x,y,stride=this.renderStride){ const tile=(Math.floor(y/8)*stride)+Math.floor(x/8);return this.pixel(tile,x&7,y&7); }
  setPixelAt(x,y,val,stride=this.renderStride){ const tile=(Math.floor(y/8)*stride)+Math.floor(x/8);this.setPixel(tile,x&7,y&7,val); }
}

function objSize(shape,size){ const ws=[[8,16,32,64],[16,32,32,64],[8,8,16,32]],hs=[[8,16,32,64],[8,8,16,32],[16,32,32,64]]; return shape<=2?{w:ws[shape][size],h:hs[shape][size]}:{w:8,h:8}; }
export class Ncer{
  constructor(data){this.data=data;if(!magic(data,0,'RECN'))throw new Error('Not NCER');const s=findSection(data,'KBEC');if(!s)throw new Error('NCER missing KBEC');const n=u16(data,s.offset+8),tableOff=u32(data,s.offset+12),table=s.offset+8+tableOff,oamBase=table+n*8;this.cells=[];for(let i=0;i<n;i++){const e=table+i*8,count=u16(data,e),attr=u16(data,e+2),raw=u32(data,e+4),oams=[];for(let j=0;j<count;j++){const o=oamBase+raw+j*6,a0=u16(data,o),a1=u16(data,o+2),a2=u16(data,o+4),shape=(a0>>>14)&3,sz=(a1>>>14)&3,d=objSize(shape,sz);let x=a1&0x1ff;if(x>=256)x-=512;let y=a0&255;if(y>=128)y-=256;const affine=!!((a0>>>8)&1);oams.push({offset:o,x,y,width:d.w,height:d.h,tile:a2&0x3ff,priority:(a2>>>10)&3,palette:(a2>>>12)&15,affine,doubleSize:affine&&!!((a0>>>9)&1),flipH:!affine&&!!((a1>>>12)&1),flipV:!affine&&!!((a1>>>13)&1),affineIndex:(a1>>>9)&31});}this.cells.push({attr,oams});} }
}

function elementSize(fmt){return fmt===0?2:fmt===1?16:fmt===2?8:fmt===3?4:2;}
function playbackIndex(anim,tick){ if(anim.frames.length===0)return 0; const durations=anim.frames.map(f=>Math.max(0,f.duration)); const total=durations.reduce((a,b)=>a+b,0)||1; const pick=(t,start=0,end=anim.frames.length-1,step=1)=>{let last=start;for(let i=start;step>0?i<=end:i>=end;i+=step){last=i;const d=durations[i];if(t<d)return i;t-=d;}return last;}; if(anim.playback===2){ const ls=anim.loopStart,pre=durations.slice(0,ls).reduce((a,b)=>a+b,0),loop=durations.slice(ls).reduce((a,b)=>a+b,0)||total;if(tick>=total)tick=pre+(tick-pre)%loop;return pick(tick);} if(anim.playback===3||anim.playback===4){ const revStart=anim.frames.length-2,revEnd=anim.playback===4?anim.loopStart:0,rev=[];for(let i=revStart;i>=revEnd;i--)rev.push(durations[i]);const revDur=rev.reduce((a,b)=>a+b,0),seq=total+revDur;if(anim.playback===4)tick%=seq;else tick=Math.min(tick,seq-1);if(tick<total)return pick(tick);return pick(tick-total,revStart,revEnd,-1);} return pick(Math.min(tick,total-1)); }
export class Nanr{
  constructor(data){this.data=data;if(!magic(data,0,'RNAN'))throw new Error('Not NANR');const s=findSection(data,'KNBA');if(!s)throw new Error('NANR missing KNBA');const n=u16(data,s.offset+8),at=u32(data,s.offset+12),fd=u32(data,s.offset+16),fe=u32(data,s.offset+20),atable=s.offset+8+at,fbase=s.offset+8+fd,ebase=s.offset+8+fe;const offs=[];for(let i=0;i<n;i++){const e=atable+i*16,c=u16(data,e),ro=u32(data,e+12),fo=fbase+ro;for(let j=0;j<c;j++)offs.push(u32(data,fo+j*8));}const uniq=[...new Set(offs)].sort((a,b)=>a-b);uniq.push(s.size-8-fe);this.animations=[];for(let i=0;i<n;i++){const e=atable+i*16,c=u16(data,e),loop=u16(data,e+2),fmt=u16(data,e+4),play=u32(data,e+8),ro=u32(data,e+12),fo=fbase+ro,frames=[];for(let j=0;j<c;j++){const frOff=fo+j*8,raw=u32(data,frOff),elOff=ebase+raw;let avail=(uniq[uniq.indexOf(raw)+1]??(s.size-8-fe))-raw,resolved=fmt,req=elementSize(fmt);if(avail===4&&u16(data,elOff+2)===0xcccc)resolved=3;else if(avail<req)resolved=avail>=16?1:avail===8?2:0;let cell=u16(data,elOff),rot=0,sx=4096,sy=4096,tx=0,ty=0;if(resolved===1){rot=s16(data,elOff+2);sx=s32(data,elOff+4);sy=s32(data,elOff+8);tx=s16(data,elOff+12);ty=s16(data,elOff+14);}else if(resolved===2){tx=s16(data,elOff+4);ty=s16(data,elOff+6);}frames.push({frameOffset:frOff,elementOffset:elOff,format:resolved,cell,duration:u16(data,frOff+4),marker:u16(data,frOff+6),rotation:rot,scaleX:sx,scaleY:sy,translateX:tx,translateY:ty});}this.animations.push({loopStart:loop<c?loop:0,format:fmt,playback:play,frames});} }
  frame(animIndex,tick){const a=this.animations[animIndex];if(!a)return null;return a.frames[playbackIndex(a,Math.max(0,tick))]||null;}
  setDuration(ai,fi,v){const f=this.animations[ai]?.frames[fi];if(!f)return;f.duration=Math.max(0,Math.min(65535,Number(v)||0));w16(this.data,f.frameOffset+4,f.duration);}
  setTranslate(ai,fi,x,y){const f=this.animations[ai]?.frames[fi];if(!f)return; if(f.format===1){f.translateX=Number(x)||0;f.translateY=Number(y)||0;w16(this.data,f.elementOffset+12,f.translateX&0xffff);w16(this.data,f.elementOffset+14,f.translateY&0xffff);}else if(f.format===2){f.translateX=Number(x)||0;f.translateY=Number(y)||0;w16(this.data,f.elementOffset+4,f.translateX&0xffff);w16(this.data,f.elementOffset+6,f.translateY&0xffff);} }
}

export class Nmcr{
  constructor(data){this.data=data;if(!magic(data,0,'RCMN'))throw new Error('Not NMCR');const s=findSection(data,'KBCM');if(!s)throw new Error('NMCR missing KBCM');const n=u16(data,s.offset+8),to=u32(data,s.offset+12),table=s.offset+8+to,base=table+n*8;this.maps=[];for(let i=0;i<n;i++){const e=table+i*8,count=u16(data,e),raw=u32(data,e+4),records=[];for(let j=0;j<count;j++){const o=base+raw+j*8;records.push({offset:o,animation:u16(data,o),x:s16(data,o+2),y:s16(data,o+4),flags:s16(data,o+6)});}this.maps.push({records});} }
  setRecord(map,idx,x,y){const r=this.maps[map]?.records[idx];if(!r)return;r.x=Number(x)||0;r.y=Number(y)||0;w16(this.data,r.offset+2,r.x&0xffff);w16(this.data,r.offset+4,r.y&0xffff);}
}

export class Nmar{
  constructor(data){this.data=data;this.entries=[]; if(!magic(data,0,'RAMN'))throw new Error('Not NMAR'); const s=findSection(data,'KNBA'); if(!s)return; const n=u16(data,s.offset+8),at=u32(data,s.offset+12),fd=u32(data,s.offset+16),fe=u32(data,s.offset+20),atable=s.offset+8+at,fbase=s.offset+8+fd,ebase=s.offset+8+fe; for(let i=0;i<n;i++){const e=atable+i*16,c=u16(data,e),fmt=u16(data,e+4),ro=u32(data,e+12),fo=fbase+ro;let map=0;if(c>0){const raw=u32(data,fo),eo=ebase+raw;map=u16(data,eo);}this.entries.push({map,label:''});} const l=findSection(data,'LBAL'); if(l){const base=l.offset+8,strBase=base+n*4,end=l.offset+l.size;for(let i=0;i<Math.min(n,this.entries.length);i++){const off=u32(data,base+i*4);let p=strBase+off,s='';while(p<end&&data[p])s+=String.fromCharCode(data[p++]);this.entries[i].label=s;}} }
  idleMap(){const e=this.entries.find(e=>e.label==='stay');return e?.map??this.entries[0]?.map??0;}
}

export function renderNcgr(ctx,ncgr,pal,{stride=ncgr.renderStride,scale=1,grid=false}={}){const {w,h}=ncgr.dimensions(stride);const off=document.createElement('canvas');off.width=w;off.height=h;const c=off.getContext('2d'),im=c.createImageData(w,h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const pi=ncgr.pixelAt(x,y,stride),o=(y*w+x)*4;if(pi===0){im.data[o+3]=0;}else{const v=pal.raw(pi),r=v&31,g=(v>>>5)&31,b=(v>>>10)&31;im.data[o]=(r<<3)|(r>>>2);im.data[o+1]=(g<<3)|(g>>>2);im.data[o+2]=(b<<3)|(b>>>2);im.data[o+3]=255;}}c.putImageData(im,0,0);ctx.canvas.width=w*scale;ctx.canvas.height=h*scale;ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,ctx.canvas.width,ctx.canvas.height);ctx.drawImage(off,0,0,w*scale,h*scale);if(grid&&scale>=6){ctx.strokeStyle='rgba(255,255,255,.12)';ctx.lineWidth=1;for(let x=0;x<=w;x++){ctx.beginPath();ctx.moveTo(x*scale+.5,0);ctx.lineTo(x*scale+.5,h*scale);ctx.stroke();}for(let y=0;y<=h;y++){ctx.beginPath();ctx.moveTo(0,y*scale+.5);ctx.lineTo(w*scale,y*scale+.5);ctx.stroke();}}return {w,h};}

function drawOamObject(ncgr,pal,oam){const cv=document.createElement('canvas');cv.width=oam.width;cv.height=oam.height;const c=cv.getContext('2d'),im=c.createImageData(cv.width,cv.height);const stride=32;for(let y=0;y<oam.height;y++)for(let x=0;x<oam.width;x++){const fx=oam.flipH?oam.width-1-x:x,fy=oam.flipV?oam.height-1-y:y,tile=oam.tile+Math.floor(fy/8)*stride+Math.floor(fx/8),pi=ncgr.pixel(tile,fx&7,fy&7),o=(y*oam.width+x)*4;if(pi){const final=ncgr.bpp===4&&pal.count>16?oam.palette*16+pi:pi;if(final<pal.count){const v=pal.raw(final),r=v&31,g=(v>>>5)&31,b=(v>>>10)&31;im.data[o]=(r<<3)|(r>>>2);im.data[o+1]=(g<<3)|(g>>>2);im.data[o+2]=(b<<3)|(b>>>2);im.data[o+3]=255;}}}c.putImageData(im,0,0);return cv;}
export function renderAnimationFrame(ctx,ncgr,pal,ncer,nanr,nmcr,mapIndex,tick,{zoom=3,stage=192}={}){ctx.canvas.width=stage*zoom;ctx.canvas.height=stage*zoom;ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,ctx.canvas.width,ctx.canvas.height);ctx.save();ctx.scale(zoom,zoom);ctx.translate(stage/2,stage/2);const map=nmcr.maps[mapIndex];if(!map){ctx.restore();return;}const list=[];let order=0;for(const rec of map.records){const fr=nanr.frame(rec.animation,tick);if(!fr||fr.cell<0||fr.cell>=ncer.cells.length)continue;for(const oam of ncer.cells[fr.cell].oams)list.push({rec,fr,oam,order:order++});}list.sort((a,b)=>b.oam.priority-a.oam.priority||b.order-a.order);for(const it of list){const {rec,fr,oam}=it,cv=drawOamObject(ncgr,pal,oam);ctx.save();ctx.translate(rec.x+fr.translateX,rec.y+fr.translateY);ctx.rotate(fr.rotation*(Math.PI*2/65536));ctx.scale((fr.scaleX||4096)/4096,(fr.scaleY||4096)/4096);let dx=oam.x,dy=oam.y;if(oam.affine&&oam.doubleSize){dx+=oam.width/2;dy+=oam.height/2;}ctx.drawImage(cv,dx,dy);ctx.restore();}ctx.restore();}
